name: Build and Release RPM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release RPM
    runs-on: ubuntu-latest
    env : 
      UPLOADERPW: ${{ secrets.UPLOADERPW }}
      UPLOADERUS: ${{ secrets.UPLOADERUS }}
      UPLOADERURL: ${{ secrets.UPLOADERURL }}
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up RPM build environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install RPM build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm git ssh sshpass curl
          
      - name: Download Nvida package.
        run: |
          chmod +x *.sh
          sh ${GITHUB_WORKSPACE}/nvidia-generate-tarballs.sh $(curl --silent "https://api.github.com/repos/NVIDIA/open-gpu-kernel-modules/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

      - name: Build RPM package
        run: |
          echo ${GITHUB_WORKSPACE}
          sed -i "s/Version:        TBD/Version:        $(curl --silent "https://api.github.com/repos/NVIDIA/open-gpu-kernel-modules/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')/" nvidia-driver.spec
          rpmbuild -ba ${GITHUB_WORKSPACE}/nvidia-driver.spec
          echo $PWD
          ls

      - name: Upload to notRPM
        run: |
          sshpass -p "$UPLOADERPW" scp -o StrictHostKeyChecking=no /home/runner/rpmbuild/RPMS/x86_64/*.rpm $UPLOADERUS@$UPLOADERURL:/var/www/html/notrpm/*.rpm
          sshpass -p "$UPLOADERPW" ssh -o StrictHostKeyChecking=no  $UPLOADERUS@$UPLOADERURL "createrepo /var/www/html/notrpm/"
